function(add_subproject name)
    if(TARGET ${name})
        message("Subproject ${name} already included, skipping")
    else()
        find_package(${name} QUIET)
        if(${name}_FOUND)
            message("Found ${name} on system")
        else()
            message("Adding ${name} as subdirectory")
            add_subdirectory(${name})
        endif()
    endif()
endfunction()
